### PR TITLE
Updated dev dependencies; updated README

### PR DESCRIPTION
**Pull request by nfreear**
Hi,

Relates to bugs :~ #4, #3.

OK, I've updated the 2 dev dependencies, and `npm test` gives `2 passes; 2 fails`.

And, I've updated the README to match the current API.

ta,

Nick / @nfreear.

### CODE REVIEW

**Comment by nfreear** [comment]
Hmm, trying to resolve merge conflicts !

**Comment by yogaraptor** [comment]
> Hmm, trying to resolve merge conflicts !

`npm i` should resolve `package-lock.json` conflicts for you automatically

(you're getting conflicts because I just merged in some dependabot PRs, sorry!)

**Comment by nfreear** [comment]
OK, need lunch before I tackle the test fails!

N.

**Comment by yogaraptor** [comment]
Looks like the lockfile needs tweaking to make `lodash.set` available to nock. This oughta do it (you can paste the below into a file and pass it to `git apply`):

```patch
---
 package-lock.json | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/package-lock.json b/package-lock.json
index 5dd1008..0bae623 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -2977,6 +2977,12 @@
       "integrity": "sha512-JNvd8XER9GQX0v2qJgsaN/mzFCNA5BRe/j8JN9d+tWyGLSodKQHKFicdwNYzWwI3wjRnaKPsGj1XkBjx/F96DQ==",
       "dev": true
     },
+    "lodash.set": {
+      "version": "4.3.2",
+      "resolved": "https://registry.npmjs.org/lodash.set/-/lodash.set-4.3.2.tgz",
+      "integrity": "sha1-2HV7HagH3eJIFrDWqEvqGnYjCyM=",
+      "dev": true
+    },
     "lodash.sortby": {
       "version": "4.7.0",
       "resolved": "https://registry.npmjs.org/lodash.sortby/-/lodash.sortby-4.7.0.tgz",
-- 
2.23.0
```

**Comment by yogaraptor** [comment]
Superceded by #7

**Comment by nfreear** [comment]
Hi,

Please close this pull #6, and use pull #7 instead ;).

Btw, the sudden appearance of the GitHub CI script, and the failure, really took me by surprise, and not in a good way! Though I understand its motivation of course ...!

All's well!

Ta,

Nick

---
(_Yep, you were ahead of this message._)

**Comment by yogaraptor** [comment]
> Btw, the sudden appearance of the GitHub CI script, and the failure, really took me by surprise, and not in a good way! Though I understand its motivation of course ...!

Apologies - honestly this is a tiny library I expected just to use for my own purposes, so when you added the pull request I decided I should make it a bit more professional around here 😅 Thanks again for the contribution.

**Comment by nfreear** [comment]
> > Btw, the sudden appearance of the GitHub CI script, and the failure, really took me by surprise, and not in a good way! Though I understand its motivation of course ...!
> 
> Apologies - honestly this is a tiny library I expected just to use for my own purposes, so when you added the pull request I decided I should make it a bit more professional around here 😅 Thanks again for the contribution.

Hi Tom, It was a good move to add CI, for just such a pull ... was just letting off steam ;) ...!

Btw, I may end up using this in [nick-bot](https://github.com/nfreear/nick-bot) (`WIP` / _working title only!_) ...

Thanks for being receptive,

Yours

Nick

**Comment by yogaraptor** [comment]
Looks interesting - good luck with it!

**Pull request closed without merging**
